name: PR Preview

on:
    pull_request_target:
        types: ['edited', 'opened', 'reopened', 'synchronize']

permissions:
    contents: write
    pull-requests: write
    actions: write

jobs:
    preview:
        if: github.event.pull_request.head.repo.full_name != github.repository
        runs-on: ubuntu-latest

        steps:
            - name: Checkout main repository
              uses: actions/checkout@v3

            - name: Fetch PR branch from fork
              run: |
                  git fetch https://github.com/${{ github.event.pull_request.head.repo.full_name }} ${{ github.event.pull_request.head.ref }}

            - name: Copy contents to preview branch
              env:
                  GITHUB_TOKEN: ${{ secrets.PAT }}
              run: |
                  PREVIEW_BRANCH="preview-${{ github.event.pull_request.number }}"
                  git checkout -b $PREVIEW_BRANCH FETCH_HEAD
                  git push origin $PREVIEW_BRANCH --force
